#!/bin/bash

mkdir Day_$1

if [ -f input.txt ]; then
	mv input.txt Day_$1/input.txt
fi

for i in "1" "2"
do
echo 'result = 0

with open("input.txt", "r") as input:
    for line in input:
        line = line.strip()

with open("output'$i'.txt", "w") as output:
    output.write(str(result))
    print(str(result))
' > ./Day_$1/part$i.py
done
